### ISSUE TITLE
Any interest in joining the trac-hacks organization?

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/trac-emoji#1]
Hi,

I'm an administrator for trac-hacks.org.  We've created an organization on GitHub and are inviting authors of trac-hacks plugins to join the organization.  Your repository could be transferred into the organization as described in the [GitHub docs](https://help.github.com/articles/transferring-a-repository/).  You'd retain full control over the repository, but the hope is that it will be easier for users on GitHub to fine trac-hacks plugins, including yours, by viewing the trac-hacks organization.

In the future, if you choose to no longer maintain the plugin, the organization would be able to provide commit access to new developers.  This would only be done with your permission, as has been the policy for plugins hosted on trac-hacks.org.  If you've already decided to no longer maintain the plugin, we would particularly appreciate you transferring the plugin to the trac-hacks organization so that we can help find new maintainers for it.

Finally, creating the trac-hacks organization is a work in progress. I appreciate if you have any suggestions on how to best support the community of trac plugin developers on GitHub. I'll be writing a blog post soon with more information and will follow-up here with a link to that post.

Kind regards,
- Ryan

**Comment by pykler** [comment]
Sounds good ... what are the steps to complete this?

**Comment by rjollos** [comment]
Thanks. Steps are short and described [here](https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts). I invited you to the organization as well.

**Comment by rjollos** [comment]
Thanks! Do you plan to continue maintaining the plugin?

**Comment by pykler** [comment]
Yes

**Comment by rjollos** [comment]
One more detail. You likely received two invitations, one was to be an organization owner, and the other was to have r/w access. You'll need to accept the second invitation as well since the first was just temporary, to allow you to move the repository.
